---
title: |
  Community Services: Projected Demographic Growth
subtitle: Projected care contacts to 2042-43, based on the 2022-23 CSDS dataset
author:
  name: Fran Barton
  email: francis.barton1@nhs.net
date: today
lang: en-GB
theme: sandstone
mainfont: "Segoe UI"
lightbox: true
embed-resources: true
fig-dpi: 108
fig-height: 10
fig-width: 16.18
fig-responsive: true
out-width: 92%
execute:
  warning: false
  echo: false
knitr:
  opts_chunk:
    dev: "ragg_png"
---

```{scss}

:root {
  // --bs-body-color: #9d928a; // SU "light charcoal" palette colour
  // --bs-body-color: #595959; // R colour grey35
  --bs-body-color: #3e3f3a; // bootswatch default grey
  --bs-body-bg: #faf0e6; // "linen"
}

```

```{r setup}
library(dplyr)
library(forcats)
library(ggplot2)
library(glue)
library(gt)
library(ragg)
library(scales)
library(StrategyUnitTheme)
library(stringr)
library(systemfonts)

contacts_data <- readr::read_rds("contacts_fy_projected_icb.rds")

text_grey <- "#3e3f3a" # sandstone theme default text colour
# text_grey <- su_theme_cols("light_charcoal")
# text_grey <- "grey35"

su_chart_theme <- function(font_family = "Segoe UI") {
  text_grey <- "#3e3f3a"
  light_bkg <- "#faf0e6" # aka "linen"
  # su_slate <- su_theme_cols("light_slate")
  dark_slate <- su_theme_cols("dark_slate")
  # l_orange <- su_theme_cols("light_orange")
  loran_tr <- "#fcdf8377" # su_theme_cols("light_orange") with transparency
  slate_tr <- "#b2b7b977" # su_theme_cols("light_slate") with transparency
  # coral_tr <- "#ff7f5077" # R coral with transparency
  ggplot2::theme(
    text = element_text(family = font_family, size = 20, colour = text_grey),
    title = element_text(hjust = 0.05),
    plot.title = element_text(size = 28, margin = margin(20, 8, 12, 18)),
    plot.subtitle = element_text(margin = margin(2, 0, 12, 20)),
    plot.caption = element_text(
      hjust = 0.96,
      size = 16,
      margin = margin(12, 6, 6, 0)
    ),
    plot.title.position = "plot",
    plot.caption.position = "plot",
    plot.background = element_rect(fill = light_bkg, colour = NA),
    plot.margin = margin(6, 24, 6, 6),
    panel.background = element_rect(fill = light_bkg),
    legend.title = element_text(hjust = 0, margin = margin(b = 8)),
    legend.background = element_rect(fill = light_bkg),
    # legend.margin = margin(r = 30),
    legend.key = element_rect(fill = light_bkg),
    legend.key.spacing.y = grid::unit(3, "mm"),
    legend.key.width = unit(12, "mm"),
    legend.text = element_text(margin = margin(l = 16), hjust = 1),
    panel.grid.major = element_line(
      colour = slate_tr,
      linewidth = 0.2,
      lineend = "butt"
    ),
    panel.grid.minor = element_line(
      colour = loran_tr,
      linewidth = 0.1,
      lineend = "butt"
    ),
    # panel.grid.major = element_blank(),
    # panel.grid.minor = element_blank(),
    axis.line = element_blank(),
    # axis.line = element_line(
    #   colour = slate_tr,
    #   linewidth = 1.5,
    #   lineend = c("round", "butt")
    # ),
    axis.ticks = element_blank(),
    # axis.ticks = element_line(
    #   colour = slate_tr,
    #   linewidth = 1.5,
    #   lineend = c("round", "butt"),
    # ),
    axis.text.x = element_text(
      size = 18,
      angle = 45,
      vjust = 0.5,
      hjust = 0.5,
      margin = margin(t = 8, b = 16)
    ),
    axis.text.y = element_text(size = 18, margin = margin(r = 8, l = 16)),
    strip.background = element_rect(fill = dark_slate, colour = NA),
    strip.text = element_text(colour = "grey95", size = 14),
    validate = TRUE
  )
}

selected_icb <- "QUA" # Black Country
# selected_icb <- "QVV" # Dorset
# selected_icb <- "QMJ" # North Central London

sub_wrap <- \(..., ww = 120) stringr::str_wrap(glue::glue(..., .sep = " "), ww)

```


```{r data-summary-functions}

add_age_groups <- function(.data) {
  .data |>
    dplyr::arrange(dplyr::pick("age_int")) |>
    dplyr::mutate(
      age_group_cat = dplyr::case_when(
        age_int == 0L ~ "0",
        age_int %in% seq(1L, 4L) ~ "1-4",
        age_int %in% seq(5L, 9L) ~ "5-9",
        age_int %in% seq(10L, 15L) ~ "10-15",
        age_int %in% seq(16L, 17L) ~ "16-17",
        age_int %in% seq(18L, 34L) ~ "18-34",
        age_int %in% seq(35L, 49L) ~ "35-49",
        age_int %in% seq(50L, 64L) ~ "50-64",
        age_int %in% seq(65L, 74L) ~ "65-74",
        age_int %in% seq(75L, 84L) ~ "75-84",
        .default = "85+"
      ),
      across(age_group_cat, forcats::fct_inorder),
      .keep = "unused"
    )
}

add_broad_age_groups <- function(.data) {
  .data |>
    dplyr::arrange(dplyr::pick("age_int")) |>
    dplyr::mutate(
      broad_age_cat = dplyr::case_when(
        age_int %in% seq(0L, 15L) ~ "0-15",
        age_int %in% seq(16L, 49L) ~ "16-49",
        age_int %in% seq(50L, 74L) ~ "50-74",
        .default = "75+"
      ),
      across(broad_age_cat, forcats::fct_inorder),
      .keep = "unused"
    )
}


```


```{r data-quality}

# Data quality calculations go here, before we filter to consistent only.

```


## National contacts projection by financial year


```{r charts1}
contacts_data <- contacts_data |>
  dplyr::filter(if_any("consistent"))

national_contacts <- contacts_data |>
  dplyr::pull("data") |>
  dplyr::bind_rows() |>
  dplyr::summarise(
    across(c("fin_year_popn", "projected_contacts"), sum),
    .by = c("fin_year", "age_int", "gender_cat") # is gender still needed?
  )

national_contacts |>
  add_broad_age_groups() |>
  dplyr::summarise(
    dplyr::across("projected_contacts", sum),
    .by = c("fin_year", "broad_age_cat")
  ) |>
  ggplot2::ggplot(aes(fin_year, projected_contacts)) +
  ggplot2::geom_line(
    aes(colour = broad_age_cat, group = broad_age_cat),
    linewidth = 1.8
  ) +
  ggplot2::labs(
    title = "Projected contacts (national) by broad age group, 2022/23 - 2042/43",
    caption = sub_wrap(
      "Sources: NHS England Community Services Dataset (2022-23),",
      "ONS Population projections"
    ),
    x = NULL,
    y = NULL
  ) +
  ggplot2::scale_y_continuous(
    labels = label_number(scale = 1e-6, suffix = "mn"),
    limits = c(0, 6e7)
  ) +
  ggplot2::scale_x_discrete(
    breaks = \(x) x[seq(1, length(x), 5)],
    labels = \(x) sub("_", "/", x)
  ) +
  scale_colour_su(name = "Age group") +
  su_chart_theme() +
  ggplot2::theme(
    legend.position = "inside",
    legend.position.inside = c(0.9, 0.6)
  )


```



## ICB-level contacts projection by financial year

```{r charts2}
icb_contacts <- contacts_data |>
  dplyr::filter(if_any("icb22cdh", \(x) x == {{ selected_icb }})) |>
  dplyr::pull("data") |>
  dplyr::bind_rows() |>
  dplyr::summarise(
    across(c("fin_year_popn", "projected_contacts"), sum),
    .by = c("fin_year", "age_int", "gender_cat") # is gender still needed?
  )

icb_contacts |>
  add_broad_age_groups() |>
  dplyr::summarise(
    dplyr::across("projected_contacts", sum),
    .by = c("fin_year", "broad_age_cat")
  ) |>
  ggplot2::ggplot(aes(fin_year, projected_contacts)) +
  ggplot2::geom_line(
    aes(colour = broad_age_cat, group = broad_age_cat),
    linewidth = 1.8
  ) +
  ggplot2::labs(
    title = "Projected contacts (single ICB) by broad age group, 2022/23 - 2042/43",
    caption = sub_wrap(
      "Sources: NHS England Community Services Dataset (2022-23),",
      "ONS Population projections"
    ),
    x = NULL,
    y = NULL
  ) +
  ggplot2::scale_y_continuous(
    labels = label_number(scale = 1e-3, suffix = "k"),
    limits = c(0, NA)
  ) +
  ggplot2::scale_x_discrete(
    breaks = \(x) x[seq(1, length(x), 5)],
    labels = \(x) sub("_", "/", x)
  ) +
  scale_colour_su(name = "Age group") +
  su_chart_theme()


```



## Projected % change in total contacts over period, by age group

```{r, charts3}
list(national = national_contacts, icb = icb_contacts) |>
  dplyr::bind_rows(.id = "type") |>
  dplyr::filter(if_any("fin_year", \(x) grepl("^20[24]2", x))) |>
  add_age_groups() |>
  dplyr::summarise(
    value = sum(.data[["projected_contacts"]]),
    .by = c("type", "fin_year", "age_group_cat")
  ) |>
  tidyr::pivot_wider(
    id_cols = c("type", "age_group_cat"),
    names_from = "fin_year",
    names_prefix = "yr_"
  ) |>
  dplyr::mutate(
    pct_change = (.data[["yr_2042_43"]] - .data[["yr_2022_23"]]) /
      .data[["yr_2022_23"]],
    .keep = "unused"
  ) |>
  ggplot2::ggplot(aes(age_group_cat, pct_change)) +
  ggplot2::geom_col(aes(fill = type), position = "dodge", width = 0.75) +
  ggplot2::geom_hline(yintercept = 0, linewidth = 0.4, colour = text_grey) +
  ggplot2::labs(
    title = "Projected % change in total contacts, by age group, 2022/23 - 2042/43",
    subtitle = sub_wrap(
      "This chart shows changes within a single selected ICB compared to",
      "national (England) changes. Change means the difference between",
      "2022/23 annual contacts and projected 2042/43 annual contacts,",
      "as a percentage of 2022/23 contacts."
    ),
    caption = sub_wrap(
      "Sources: NHS England Community Services Dataset (2022-23),",
      "ONS Population projections"
    ),
    x = "Age group",
    y = "% change"
  ) +
  ggplot2::scale_y_continuous(
    labels = label_percent(suffix = ""),
    limits = c(-0.25, NA)
  ) +
  scale_fill_su(name = NULL) +
  su_chart_theme() +
  ggplot2::theme(
    legend.position = "inside",
    legend.position.inside = c(0.15, 0.72),
    legend.text = element_text(margin = margin(l = 6), hjust = 0)
  )


```


## Contacts per 1000 population, 2022/23, by age group

```{r charts4}
list(national = national_contacts, icb = icb_contacts) |>
  dplyr::bind_rows(.id = "type") |>
  dplyr::filter(if_any("fin_year", \(x) x == "2022_23")) |>
  add_age_groups() |>
  dplyr::summarise(
    across(c("fin_year_popn", "projected_contacts"), sum),
    .by = c("type", "age_group_cat")
  ) |>
  dplyr::mutate(
    contacts_rate = .data[["projected_contacts"]] / .data[["fin_year_popn"]],
    .keep = "unused"
  ) |>
  ggplot2::ggplot(aes(age_group_cat, contacts_rate)) +
  ggplot2::geom_col(aes(fill = type), position = "dodge", width = 0.75) +
  ggplot2::labs(
    title = "Contacts per 1,000 population, 2022/23, by age group",
    subtitle = sub_wrap(
      "This chart shows the contact rate by age group within a single selected",
      "ICB, compared to the national (England) rate."
    ),
    caption = sub_wrap(
      "Sources: NHS England Community Services Dataset (2022-23),",
      "ONS Population projections"
    ),
    x = "Age group",
    y = "Contacts / 1000 people"
  ) +
  ggplot2::scale_y_continuous(labels = label_number(scale = 1e3)) +
  scale_fill_su(name = NULL) +
  su_chart_theme() +
  ggplot2::theme(
    legend.position = "inside",
    legend.position.inside = c(0.15, 0.72),
    legend.text = element_text(margin = margin(l = 6), hjust = 0)
  )

```
